[package]
name = "realtime-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
delphi-auth.workspace = true
delphi-config.workspace = true
delphi-contracts.workspace = true
delphi-nats.workspace = true
delphi-storage.workspace = true
futures.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
