[package]
name = "document-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
delphi-config.workspace = true
delphi-document-adapters.workspace = true
delphi-document-app.workspace = true
tokio.workspace = true
tracing.workspace = true
